-- Run this once if AG_GL_ACCOUNT_HISTORY_CASES was created from the first POC schema.
-- These columns preserve the additional fields in gl_account_history_poc_120.xlsx.

ALTER TABLE AG_GL_ACCOUNT_HISTORY_CASES ADD (
    INVOICE_ID VARCHAR2(200 CHAR),
    INVOICE_DISTRIBUTION_ID VARCHAR2(200 CHAR),
    DIST_CODE_COMBINATION_ID VARCHAR2(200 CHAR),
    VENDOR_ID VARCHAR2(200 CHAR),
    VENDOR_SITE_ID VARCHAR2(200 CHAR),
    BUSINESS_UNIT_ID VARCHAR2(200 CHAR),
    LEDGER_ID VARCHAR2(200 CHAR),
    CHART_OF_ACCOUNTS_ID VARCHAR2(200 CHAR),
    DATASET_TYPE VARCHAR2(100 CHAR),
    IS_SYNTHETIC VARCHAR2(20 CHAR),
    SOURCE_INVOICE_DISTRIBUTION_ID VARCHAR2(200 CHAR),
    SYNTHETIC_TYPE VARCHAR2(100 CHAR)
);

